# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d52ce71ad2202965cf48917feab46b7b3e3fa798f0e962c85fae63615d11d002e9a2a7ae2768e3864ab82c6703eaa2d2fe7cbfcab88298b148e07cd4028ab4e1

test:
  secret_key_base: fdc1ffe5a7fd39e453c83b2663a3e07a781af72bfb50809cb768e6b898d872a228e50c2d335dd095aac35365e1564d3a09eea54d102c0e0d95f0a36146506e3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
